name: Build and Publish Docker Image

on:
  push:
    branches: ['main']

# This fixes the Node.js 20 Deprecation Warning!
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          # THIS IS THE FIX: We tell Docker to look inside the subfolder!
          context: ./fleet_maintenance
          push: true
          tags: ghcr.io/officialxndr/fleet-maintenance-addon:latest